<?php
/** @var \CodeCave\Ean\Block\Info\Ean $block */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd>

        <strong><?= $block->escapeHtml(__('EAN-nummer')) ?></strong>
        <span><?= $block->escapeHtml($block->getInfo()->getAdditionalInformation('ean_number')) ?></span>
        <br/>

        <strong><?= $block->escapeHtml(__('Reference')) ?></strong>
        <span><?= $block->escapeHtml($block->getInfo()->getAdditionalInformation('ean_ref')) ?></span>
        <br/>
        <strong><?= $block->escapeHtml(__('Institution')) ?></strong>
        <span><?= $block->escapeHtml($block->getInfo()->getAdditionalInformation('ean_ins')) ?></span>
    </dd>
</dl>
